Intranet.Web/Controllers/StudentCourseController.cs
using Intranet.Common.Enums;
using Intranet.Common.ViewModels;
using Intranet.Services.Entities;
using System.Collections.Generic;
using System.Web.Mvc;

namespace Intranet.Web.Controllers
{
    [Authorize(Roles = "Student")]
    public class StudentCourseController : Controller
    {
        private StudentService _studentservice;
        public StudentCourseController(StudentService studentservice)
        {
            _studentservice = studentservice;
        }
        // GET: StudentCourse
        public ActionResult Index(StudentCourseViewModel model)
        {
            ViewBag.Title = "Cursos";
            ViewBag.SelectedMenu = EnumStudentMenu.Cursos;

            model.userName = User.Identity.Name;
            model.idSearchDepartment = model.idSearchDepartment;
            model.CourseName = (string.IsNullOrEmpty(model.CourseName)) ? "" : model.CourseName;

            var cursos = _studentservice.getStudentCourses(model);
            return View(cursos);
        }

        public PartialViewResult GetScoreDetails(int courseId)
        {
            var score = _studentservice.getScoreDetails(courseId,User.Identity.Name);
            return PartialView("_PartialScoreDetails", score);
        }

        public PartialViewResult GetRecord(int courseId)
        {

            return PartialView("Shared/_PartialRecordDetails", null);
        }
    }
}

Intranet.Web/Controllers/StudentEnrollmentController.cs
using Intranet.Common.Enums;
using Intranet.Common.ViewModels;
using Intranet.Services.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;

namespace Intranet.Web.Controllers
{
    [Authorize(Roles = "Student")]
    public class StudentEnrollmentController : Controller
    {
        private EnrollmentService _enrollmentservice;
        public StudentEnrollmentController(EnrollmentService enrollmentService)
        {
            _enrollmentservice = enrollmentService;
        }
        // GET: StudentEnrollment
        public ActionResult Index()
        {

            ViewBag.Title = "Matricula";
            ViewBag.SelectedMenu = EnumStudentMenu.Matricula;
            var courses = _enrollmentservice.getAvailableCourses();
            return View(courses);
        }

        public ActionResult Details(int id)
        {
            ViewBag.Title = "Detalle de Curso";
            ViewBag.SelectedMenu = EnumStudentMenu.Matricula;
            var detailCourse = _enrollmentservice.getCoursesDetail(id);
            return View(detailCourse);
        }

        public ActionResult Enrollment(int id)
        {
            ViewBag.Title = "Matricula OnLine";
            ViewBag.SelectedMenu = EnumStudentMenu.Matricula;
            var detailCourse = _enrollmentservice.getCoursesDetail(id);
            var enroll = new EnrollmentViewModel();
            enroll.Courseid = detailCourse.Id;
            enroll.CourseName = detailCourse.CourseName;

            IEnumerable<EnumPaymentType> paymentTypes = Enum.GetValues(typeof(EnumPaymentType))
                                                       .Cast<EnumPaymentType>();

            //enroll.PaymentTypeList = from types in paymentTypes
            //                         select new SelectListItem
            //                         {
            //                             Text = types.ToString(),
            //                             Value = ((int)types).ToString()
            //                         };
            return View(enroll);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Enrollment(EnrollmentViewModel model)
        {
            //ViewBag.Title = "Matricula OnLine";
            //ViewBag.SelectedMenu = EnumStudentMenu.Matricula;
            //if (ModelState.IsValid)
            //{
            //    try
            //    {
            //        model.Email = User.Identity.Name;
            //        _studentService.updateStudentInfo(model);
            //        return View(model);
            //    }
            //    catch (Exception ex)
            //    {
            //        ModelState.AddModelError("Error", ex);
            //        return View(model);
            //    }
            //}
            //ModelState.AddModelError("Error", "Model is invalid");
            return View(model);
        }
    }
}

Intranet.Web/Controllers/StudentHomeController.cs
using Intranet.Common.Enums;
using Intranet.Common.ViewModels;
using Intranet.Services.Entities;
using System;
using System.Web.Mvc;

namespace Intranet.Web.Controllers
{
    [Authorize(Roles = "Student")]
    public class StudentHomeController : Controller
    {
        StudentService _studentService;
        public StudentHomeController(StudentService studentService)
        {
            _studentService = studentService;
        }

        public ActionResult Index()
        {
            ViewBag.Title = "Home";
            return View();
        }

        public ActionResult Details()
        {
            ViewBag.Title = "Datos Personales";
            ViewBag.SelectedMenu = EnumStudentMenu.DatosPersonales;
            var student = _studentService.getStudentDetails(User.Identity.Name);
            return View(student);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Details(StudentDetailsViewModel model)
        {
            ViewBag.Title = "Datos Personales";
            ViewBag.SelectedMenu = EnumStudentMenu.DatosPersonales;
            if (ModelState.IsValid)
            {
                try
                {
                    model.Email = User.Identity.Name;
                    _studentService.updateStudentInfo(model);
                    return View(model);
                }
                catch (Exception ex)
                {
                    ModelState.AddModelError("Error", ex);
                    return View(model);
                }
            }
            ModelState.AddModelError("Error", "Model is invalid");
            return View(model);
        }

    }
}

Intranet.Web/Controllers/StudentScoreController.cs
using Intranet.Common.Enums;
using System.Web.Mvc;

namespace Intranet.Web.Controllers
{
    [Authorize(Roles = "Student")]
    public class StudentScoreController : Controller
    {
        // GET: StudentScore
        public ActionResult Index()
        {
            ViewBag.Title = "Notas Actuales";
            ViewBag.SelectedMenu = EnumStudentMenu.Notas;
            return View();
        }
    }
}

Intranet.Web/Views/Shared/_AdminMenu.cshtml
@using Intranet.Common.Enums
<div class="col-xs-6 col-sm-3 sidebar-offcanvas">
    <div class="list-group">
        @Html.ActionLink("Datos Personales", "Details", "StudentHome", null, new { @class = (ViewBag.SelectedMenu == EnumStudentMenu.DatosPersonales ? "list-group-item active" : "list-group-item") })
        @*@Html.ActionLink("Registro de Cursos", "Index", "StudentCourse", null, new { @class = (ViewBag.SelectedMenu == EnumStudentMenu.Cursos ? "list-group-item active" : "list-group-item") })
        @Html.ActionLink("Registro de Alumnos", "Index", "StudentEnrollment", null, new { @class = (ViewBag.SelectedMenu == EnumStudentMenu.RegistroAlumnos ? "list-group-item active" : "list-group-item") })
        @Html.ActionLink("Registro de Profesores", "Index", "StudentEnrollment", null, new { @class = (ViewBag.SelectedMenu == EnumStudentMenu.Matricula ? "list-group-item active" : "list-group-item") })
        @Html.ActionLink("Notas", "Index", "StudentScore", null, new { @class = (ViewBag.SelectedMenu == EnumStudentMenu.Notas ? "list-group-item active" : "list-group-item") })*@
    </div>
</div>

Intranet.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Intranet Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/unobtrusive")
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/calendar")    
    @RenderSection("scripts", required: false)
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Instituto ABC", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Acerca", "About", "Home")</li>
                    <li>@Html.ActionLink("Contacto", "Contact", "Home")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content" style=" padding-top:12px !important;">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Intranet Instituto ABC</p>
        </footer>
    </div>
</body>
</html>

Intranet.Web/Views/Shared/_StudentMenu.cshtml
@using Intranet.Common.Enums
    <div class="col-xs-6 col-sm-3 sidebar-offcanvas">
        <div class="list-group">
            @Html.ActionLink("Datos Personales", "Details", "StudentHome", null, new { @class = (ViewBag.SelectedMenu == EnumStudentMenu.DatosPersonales ? "list-group-item active" : "list-group-item") })
            @Html.ActionLink("Cursos", "Index", "StudentCourse", null, new { @class = (ViewBag.SelectedMenu == EnumStudentMenu.Cursos ? "list-group-item active" : "list-group-item") })
            @*@Html.ActionLink("Notas Actuales", "Index", "StudentScore", null, new { @class = (ViewBag.SelectedMenu == EnumStudentMenu.Notas ? "list-group-item active" : "list-group-item") })*@
            @Html.ActionLink("Matricula OnLine", "Index", "StudentEnrollment", null, new { @class = (ViewBag.SelectedMenu == EnumStudentMenu.Matricula ? "list-group-item active" : "list-group-item") })
        </div>
    </div>